version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: giorgiy
      POSTGRES_PASSWORD: armyanin
      POSTGRES_DB: Homework
    ports:
      - "65432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
